# your-deployment-file.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mounica-flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mounica-flask-app
  template:
    metadata:
      labels:
        app: mounica-flask-app
    spec:
      containers:
      - name: mounica-flask-app
        image: gcr.io/automatedcicd-gcp/mounica-flast-image:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: mounica-flask-app-service
spec:
  selector:
    app: mounica-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
