steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        us-central1-docker.pkg.dev/automated-cicd-gcp/cicdpipeline/mounica-python-web-app:$COMMIT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        us-central1-docker.pkg.dev/automated-cicd-gcp/cicdpipeline/mounica-python-web-app:$COMMIT_SHA
  - name: gcr.io/cloud-builders/gcloud
    args:
      - container
      - clusters
      - get-credentials
      - app-cluster
      - '--zone=us-central1'
  - name: gcr.io/cloud-builders/kubectl
    env:
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      - CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true
      - CLOUDSDK_COMPUTE_REGION=us-central1
      - CLOUDSDK_COMPUTE_ZONE=us-central1
      - CLOUDSDK_CONTAINER_CLUSTER=app-cluster
    args:
      - apply
      - '-f'
      - app.yaml
    dir: .
options:
  logging: CLOUD_LOGGING_ONLY

